### ISSUE TITLE
Compile on Godbolt link maybe broken

### ISSUE THREAD

**Issue by ckormanyos** [imahjoub/hash_sha256#88]
Hi Iliass (@imahjoub) I notice that the "try it on Godbolt" button links to code that fails compile.

This [link](https://godbolt.org/z/6o77bqf6M) is one potential solution that repairs it. There are several possible ways to repair and i'm not sure which one you like. That link does link to one possible correciotn.

Nice work on this repo iliass.

**Comment by imahjoub** [comment]
Hi Chris,

yes I changed the code and forgot to update Godbolt link. I will use your link.

Many thanks :)

**Comment by imahjoub** [comment]
issue handled in [PR#89](https://github.com/imahjoub/hash_sha256/pull/89)

**Comment by ckormanyos** [comment]
Thanks Iliass it works (@imahjoub)
